INSERT INTO categories (level) values (1);
INSERT INTO categories (level) values (2);
INSERT INTO categories (level) values (3);
INSERT INTO categories (level) values (4);
INSERT INTO categories (level) values (5);

INSERT INTO questions (id, text) values (1, '¿Qué palabra se usa para referirse a los abdominales bien marcados?');
INSERT INTO questions (id, text) values (2, '¿Qué palabra aparece tradicionalmente en la pantalla al terminar un largometraje?');
INSERT INTO questions (id, text) values (3, '¿Cuál de los siguientes sería atraído por un imán?');
INSERT INTO questions (id, text) values (4, '¿Cuál de estos nombres no aparece en el título de una obra de Shakespeare?');
INSERT INTO questions (id, text) values (5, '¿Cuál es el lugar de origen del whisky escocés?');
INSERT INTO questions (id, text) values (6, 'Una locomotora valiente es la heroína de un clásico libro infantil llamado La locomotora que sí...');
INSERT INTO questions (id, text) values (7, '¿Cuál de estos es un instrumento musical?');
INSERT INTO questions (id, text) values (8, '¿Qué significa la abreviación en inglés "BFF"?');
INSERT INTO questions (id, text) values (9, '¿Con qué apodo se conoce a la estrella de cine y luchador profesional Dwayne Johnson?');
INSERT INTO questions (id, text) values (10, '¿Cómo se llamaba la banda cuyo líder era Jim Morrison?');
INSERT INTO questions (id, text) values (11, '¿Qué edad tenía Drew Barrymore cuando protagonizó la película “E.T.”?');
INSERT INTO questions (id, text) values (12, 'La nectarina es:');
INSERT INTO questions (id, text) values (13, 'El amaretto es un licor a base de:');
INSERT INTO questions (id, text) values (14, '¿Cuántos astronautas han tenido el privilegio de andar sobre la luna?');
INSERT INTO questions (id, text) values (15, 'El actor Daniel Ratcliffe ha encarnado en la gran pantalla a uno de estos personajes:');
INSERT INTO questions (id, text) values (16, '¿Cuál de los siguientes hombres no tiene un elemento químico llamado como él?');
INSERT INTO questions (id, text) values (17, '¿En la corte de qué rey pasó Leonardo Da Vinci los dos últimos años de su vida?');
INSERT INTO questions (id, text) values (18, '¿Cuál de estas películas de los 80 se estrenó primero?');
INSERT INTO questions (id, text) values (19, '¿Cuál de estas canciones debutó primero?');
INSERT INTO questions (id, text) values (20, '¿Qué santo fundó la Abadía de Montecasino?');
INSERT INTO questions (id, text) values (21, 'De acuerdo con la Oficina de Referencia de la Población (Population Reference Bureau) ¿Cuál es el número aproximado de personas que han vivido en la Tierra?');
INSERT INTO questions (id, text) values (22, '¿Con qué letra comienza la palabra del tomo 21 de la Enciclopedia Espasa?');
INSERT INTO questions (id, text) values (23, '¿Quién fue el primero en recibir un premio Nobel de Literatura?');
INSERT INTO questions (id, text) values (24, '¿Los neurólogos creen que la corteza prefrontal del cerebro se activa cuando haces qué?');
INSERT INTO questions (id, text) values (25, 'Si un día decidieras sembrar semillas de Quercus robur. ¿Qué crecería?');

INSERT INTO answers (id, text, correct_answer) values (1, 'A. Lavadora  B. Lavadero  C. Lavanda  D. Lavaloza', 'B');
INSERT INTO answers (id, text, correct_answer) values (2, 'A. Fin  B. Conclusión  C. Final  D. Acabó', 'A');
INSERT INTO answers (id, text, correct_answer) values (3, 'A. Metal  B. Plástico  C. Madera  D. El hombre equivocado', 'A');
INSERT INTO answers (id, text, correct_answer) values (4, 'A. Hamlet  B. Romeo  C. Macbeth  D. Darren', 'D');
INSERT INTO answers (id, text, correct_answer) values (5, 'A. Irlanda  B. Gales  C. Estados Unidos  D. Escocia', 'D');
INSERT INTO answers (id, text, correct_answer) values (6, 'A. The Doors  B. The Windows  C. The Floors  D. The Ceilings', 'A');
INSERT INTO answers (id, text, correct_answer) values (7, 'A. El Bloque  B. El Peñasco  C. La Piedra  D. La Roca', 'D');
INSERT INTO answers (id, text, correct_answer) values (8, 'A. Buff Fit Fella  B. Bye for Five  C. Boy Friend Furious  D. Best Friends Forever', 'D');
INSERT INTO answers (id, text, correct_answer) values (9, 'A. Mandrágora  B. Mandalay  C. Mandolina  D. Mandril', 'C');
INSERT INTO answers (id, text, correct_answer) values (10, 'A. Llegó  B. Logró  C. Pudo  D. Alcanzó', 'C');
INSERT INTO answers (id, text, correct_answer) values (11, 'A. Luke Skywalker  B. Harry Potter  C. Indiana Jones  D. Superman', 'B');
INSERT INTO answers (id, text, correct_answer) values (12, 'A. Doce  B. Tres  C. Veinte  D. Seis', 'A');
INSERT INTO answers (id, text, correct_answer) values (13, 'A. Manzana  B. Café  C. Anís  D. Almendra', 'D');
INSERT INTO answers (id, text, correct_answer) values (14, 'A. Una fruta  B. Un insecto  C. Una hormona  D. Una enzima', 'A');
INSERT INTO answers (id, text, correct_answer) values (15, 'A. 9 años  B. 7 años  C. 8 años  D. 6 años"', 'D');
INSERT INTO answers (id, text, correct_answer) values (16, 'A. Benedicto  B. Bernardo  C. Buenaventura  D. Bonifacio', 'A');
INSERT INTO answers (id, text, correct_answer) values (17, 'A. The Second You Sleep de Saybia  B. I Want What’s She’s Got de eyeQ  C. Beautiful Day de U2  D. Erase/Rewind de The Cardigans', 'D');
INSERT INTO answers (id, text, correct_answer) values (18, 'A. Cocodrilo Dundee  B. Entre pillos anda el juego  C. Arma letal  D. Regreso al futuro', 'B');
INSERT INTO answers (id, text, correct_answer) values (19, 'A. Enrique IV  B. Carlos III  C. Luis XII  D. Francisco I', 'D');
INSERT INTO answers (id, text, correct_answer) values (20, 'A. Albert Einstein  B. Niels Bohr  C. Isaac Newton  D. Enrico Fermi', 'C');
INSERT INTO answers (id, text, correct_answer) values (21, 'A. Árbol  B. Flores  C. Verduras  D. Grano', 'A');
INSERT INTO answers (id, text, correct_answer) values (22, 'A. Tienes un ataque de pánico  B. Recuerdas un nombre  C. Entiendes una broma  D. Escuchas música', 'C');
INSERT INTO answers (id, text, correct_answer) values (23, 'A. Novelista  B. Dramaturgo  C. Poeta  D. Ensayista', 'C');
INSERT INTO answers (id, text, correct_answer) values (24, 'A. E  B. F  C. G  D. H', 'A');
INSERT INTO answers (id, text, correct_answer) values (25, 'A. 108 000 millones  B. 180 000 millones  C. 1 110 000 millones  D. 1 108 000 millones', 'A');
